---
#- name: Stop psql service
#  ansible.builtin.service:
#    name: postgresql
#    state: stopped
#    enabled: false

- name: Remove psql packages
  ansible.builtin.yum:
    name:
      - postgresql.x86_64
      - postgresql-libs.x86_64
      - postgresql-server.x86_64
    state: absent

- name: Recursively remove psql directory
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  with_items:
    - /var/lib/pgsql
    - /psql

#- name: Check whether a package called postgres\* is installed
#  ansible.builtin.debug:
#    msg: "{{ ansible_facts.packages['postgres\*'] | length }} versions of postgres are installed!"
#  when: "'postgres\*' in ansible_facts.packages"

