---
- name: Upgrade all packages
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: Install epel rpm from a remote repo
  ansible.builtin.yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install Ansible
  ansible.builtin.yum:
    name: ansible
    state: present

- name: write hostname using jinja2
  ansible.builtin.template:
    src: templates/ansible_inventory.conf.j2
    dest: "{{ ansible.inventory }}"

- name: Execute setup.sh
  script: /home/ansible/ansible-tower-setup-3.8.6-2/setup.sh
