---
- name: Start_Enable postgresql
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

- name: Restart_Enable postgresql
  ansible.builtin.service:
    name: postgresql
    state: restarted
