---
- name: Start service
  ansible.builtin.service:
    name: postgresql
    state: started

- name: Enable service
  ansible.builtin.service:
    name: postgresql
    enabled: true

- name: Restart service
  ansible.builtin.service:
    name: postgresql
    state: restarted

- name: Stop service
  ansible.builtin.service:
    name: postgresql
    state: stopped
