---

#- name: Install and setup postgresql
#  hosts: psql
#  become: true
#  gather_facts: false
#  roles:
#    - role: psql

- name: Setup or Remove psql with task specification
  hosts: psql
  become: true
  gather_facts: false
  tasks:
    - name: psql
      include_role:
        name: psql
        tasks_from: remove_psql
